controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: /compte/logout
    controller: App\Controller\LoginController::index
    methods: GET
